### ISSUE TITLE
[Tabbar] Tabbar组件中的TabItem添加key属性(key的类型可以是string或number)作为唯一标识，调用change方法时，可以传入key

### ISSUE THREAD

**Issue by qinains** [yuncishuzi/iui-design#2]
### 这个功能解决了什么问题

切换不同的角色，底部需要让某个tabItem点亮。当底部tabItem有增删时，如果只有传index，就很容易搞混。change方法中的index传入key，就很安全

### 你建议的方案是什么

tabItem添加key属性用来做唯一标识。tabbar的change方法中index类型是string或number，当是string的时候，跟tabItem中的key匹配

**Comment by yisa1023** [comment]
@qinains 感谢您提出了 issue，我们将尽快检查并回复你。
